
title: DataIntel
email: hello@dataintel.ai
description: >-
  Leveraging aspect-based sentiment analysis to bring intelligence to your feedback or review data
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /blog/:title
separator: "–"
google_analytics_id: UA-124570982-1
default_image: /assets/images/logo.png

defaults:
  -
    scope:
      path: ""
    values:
      image: "/assets/images/logo.png" # Default site image for Open Graph
  -
    scope:
      path: "assets/images"
    values:
      image: true

markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
